// Code generated by goboot. DO NOT EDIT.

package cfge2e

import (
	"context"
	"fmt"
	"github.com/zombocoder/goboot/compiler/testdata/cfgapp"
	"github.com/zombocoder/goboot/runtime"
	"github.com/zombocoder/goboot/runtime/config"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Engine           *cfgapp.Engine
	ServerProperties cfgapp.ServerProperties
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents(configSource config.Source) (*Components, error) {
	serverProperties, err := LoadServerProperties(configSource)
	if err != nil {
		return nil, err
	}
	engine := cfgapp.NewEngine(serverProperties)

	return &Components{
		Engine:           engine,
		ServerProperties: serverProperties,
	}, nil
}

// LoadServerProperties loads cfgapp.ServerProperties from configuration under the "server" prefix.
func LoadServerProperties(source config.Source) (cfgapp.ServerProperties, error) {
	var out cfgapp.ServerProperties
	if err := config.Bind("server", source, &out); err != nil {
		return out, fmt.Errorf("load ServerProperties: %w", err)
	}
	return out, nil
}

// buildLifecycle registers component lifecycle hooks in construction order.
func buildLifecycle(components *Components) *runtime.Lifecycle {
	lc := runtime.NewLifecycle(0)
	lc.Register("github.com/zombocoder/goboot/compiler/testdata/cfgapp:Engine", func(ctx context.Context) error { return components.Engine.Start(ctx) }, func(ctx context.Context) error { return components.Engine.Stop() })
	return lc
}

// NewApplication builds the components and assembles a runnable application.
func NewApplication(configSource config.Source) (*runtime.Application, error) {
	components, err := buildComponents(configSource)
	if err != nil {
		return nil, err
	}
	lc := buildLifecycle(components)
	return &runtime.Application{Lifecycle: lc, Scheduler: nil}, nil
}
