// Code generated by goboot. DO NOT EDIT.

package resiliencee2e

import (
	"context"
	"github.com/zombocoder/goboot/compiler/testdata/resilienceapp"
	"github.com/zombocoder/goboot/runtime"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Flaky             *resilienceapp.FlakyService
	FlakyServiceProxy resilienceapp.Flaky
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents(proxyDeps runtime.ProxyDependencies) (*Components, error) {
	flaky := resilienceapp.NewFlakyService()
	flakyServiceProxy := NewFlakyServiceProxy(flaky, proxyDeps)

	return &Components{
		Flaky:             flaky,
		FlakyServiceProxy: flakyServiceProxy,
	}, nil
}

// FlakyServiceProxy is the generated interception proxy for FlakyService.
type FlakyServiceProxy struct {
	target      *resilienceapp.FlakyService
	transaction runtime.TransactionManager
	tracer      runtime.Tracer
	metrics     runtime.MethodMetrics
	authorizer  runtime.Authorizer
}

// NewFlakyServiceProxy builds the FlakyServiceProxy.
func NewFlakyServiceProxy(target *resilienceapp.FlakyService, deps runtime.ProxyDependencies) *FlakyServiceProxy {
	return &FlakyServiceProxy{target: target, transaction: deps.Transactions, tracer: deps.Tracer, metrics: deps.Metrics, authorizer: deps.Authorizer}
}

func (p *FlakyServiceProxy) Attempt(a0 context.Context) (r0 int, err error) {
	err = runtime.Retry(a0, runtime.RetryPolicy{MaxAttempts: 4, Delay: 1000000, Multiplier: 2, MaxDelay: 10000000}, func(ctx context.Context) error {
		var e error
		r0, e = p.target.Attempt(ctx)
		return e
	})
	return
}

func (p *FlakyServiceProxy) Slow(a0 context.Context) (err error) {
	a0, cancel := context.WithTimeout(a0, 20000000)
	defer cancel()
	err = p.target.Slow(a0)
	return
}
