// Code generated by goboot. DO NOT EDIT.

package proxye2e

import (
	"context"
	"github.com/zombocoder/goboot/compiler/testdata/proxyapp"
	"github.com/zombocoder/goboot/runtime"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	OrderController   *proxyapp.OrderController
	OrderService      *proxyapp.OrderService
	OrderServiceProxy proxyapp.OrderUseCase
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents(proxyDeps runtime.ProxyDependencies) (*Components, error) {
	orderService := proxyapp.NewOrderService()
	orderServiceProxy := NewOrderServiceProxy(orderService, proxyDeps)
	orderController := proxyapp.NewOrderController(orderServiceProxy)

	return &Components{
		OrderController:   orderController,
		OrderService:      orderService,
		OrderServiceProxy: orderServiceProxy,
	}, nil
}

// OrderServiceProxy is the generated interception proxy for OrderService.
type OrderServiceProxy struct {
	target      *proxyapp.OrderService
	transaction runtime.TransactionManager
	tracer      runtime.Tracer
	metrics     runtime.MethodMetrics
}

// NewOrderServiceProxy builds the OrderServiceProxy.
func NewOrderServiceProxy(target *proxyapp.OrderService, deps runtime.ProxyDependencies) *OrderServiceProxy {
	return &OrderServiceProxy{target: target, transaction: deps.Transactions, tracer: deps.Tracer, metrics: deps.Metrics}
}

func (p *OrderServiceProxy) CreateOrder(a0 context.Context, a1 string) (r0 string, err error) {
	a0, span := p.tracer.Begin(a0, "orders.create")
	defer func() { span.End(err) }()
	err = p.transaction.WithinTransaction(a0, runtime.TransactionOptions{}, func(ctx context.Context) error {
		var e error
		r0, e = p.target.CreateOrder(ctx, a1)
		return e
	})
	if err != nil {
		p.metrics.RecordFailure("orders.create")
		return
	}
	p.metrics.RecordSuccess("orders.create")
	return
}

func (p *OrderServiceProxy) GetOrder(a0 context.Context, a1 string) (string, error) {
	return p.target.GetOrder(a0, a1)
}
