package main

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// runCLI invokes the CLI with args and captures stdout and stderr.
func runCLI(args ...string) (code int, stdout, stderr string) {
	var o, e bytes.Buffer
	code = run(args, &o, &e)
	return code, o.String(), e.String()
}

// compilerDir is the path to the compiler package (with its testdata) from the
// cmd/goboot test working directory.
const compilerDir = "../../compiler"

func TestVersion(t *testing.T) {
	code, out, _ := runCLI("version")
	if code != 0 {
		t.Fatalf("version exit = %d", code)
	}
	if !strings.Contains(out, CLIVersion) {
		t.Errorf("version output = %q, want it to contain %q", out, CLIVersion)
	}
}

func TestUnknownCommand(t *testing.T) {
	if code, _, _ := runCLI("bogus"); code != 2 {
		t.Errorf("unknown command exit = %d, want 2", code)
	}
	if code, _, _ := runCLI(); code != 2 {
		t.Errorf("no command exit = %d, want 2", code)
	}
}

func TestHelp(t *testing.T) {
	code, out, _ := runCLI("help")
	if code != 0 {
		t.Fatalf("help exit = %d", code)
	}
	if !strings.Contains(out, "generate") || !strings.Contains(out, "validate") {
		t.Errorf("help missing commands: %q", out)
	}
}

func TestValidateSuccess(t *testing.T) {
	code, out, errOut := runCLI("validate", "-dir", compilerDir, "./testdata/diapp/...")
	if code != 0 {
		t.Fatalf("validate exit = %d, stderr=%s", code, errOut)
	}
	if !strings.Contains(out, "ok") {
		t.Errorf("validate output = %q", out)
	}
}

func TestValidateFailsOnCycle(t *testing.T) {
	code, _, errOut := runCLI("validate", "-dir", compilerDir, "./testdata/cycle")
	if code == 0 {
		t.Fatalf("validate should fail on a dependency cycle")
	}
	if !strings.Contains(errOut, "GOBDI005") {
		t.Errorf("expected cycle diagnostic in stderr, got %q", errOut)
	}
}

func TestValidateStrictPromotesWarning(t *testing.T) {
	// The primary fixture resolves cleanly but declares no @Application, which
	// is a warning. Without strict it passes; with strict the warning fails.
	if code, _, errOut := runCLI("validate", "-dir", compilerDir, "./testdata/primary"); code != 0 {
		t.Errorf("non-strict validate should pass, exit=%d stderr=%s", code, errOut)
	}
	if code, _, _ := runCLI("validate", "-dir", compilerDir, "-strict", "./testdata/primary"); code == 0 {
		t.Errorf("strict validate should fail on the no-@Application warning")
	}
}

func TestGraphFormats(t *testing.T) {
	for _, format := range []string{"text", "mermaid", "dot", "json"} {
		code, out, errOut := runCLI("graph", "-dir", compilerDir, "-format", format, "./testdata/diapp/...")
		if code != 0 {
			t.Fatalf("graph -format %s exit = %d, stderr=%s", format, code, errOut)
		}
		if out == "" {
			t.Errorf("graph -format %s produced no output", format)
		}
	}
	if code, _, _ := runCLI("graph", "-dir", compilerDir, "-format", "bogus", "./testdata/diapp/..."); code != 2 {
		t.Errorf("unknown graph format exit = %d, want 2", code)
	}
}

func TestGraphMermaidShape(t *testing.T) {
	_, out, _ := runCLI("graph", "-dir", compilerDir, "-format", "mermaid", "./testdata/diapp/...")
	if !strings.HasPrefix(out, "flowchart TD") {
		t.Errorf("mermaid output missing header: %q", out[:min(40, len(out))])
	}
}

func TestInit(t *testing.T) {
	dir := t.TempDir()
	code, out, errOut := runCLI("init", "-dir", dir)
	if code != 0 {
		t.Fatalf("init exit = %d, stderr=%s", code, errOut)
	}
	if !strings.Contains(out, "goboot.yaml") {
		t.Errorf("init output = %q", out)
	}
	if _, err := os.Stat(filepath.Join(dir, "goboot.yaml")); err != nil {
		t.Fatalf("goboot.yaml not created: %v", err)
	}
	// Second init without -force fails.
	if code, _, _ := runCLI("init", "-dir", dir); code == 0 {
		t.Errorf("second init without -force should fail")
	}
	// With -force it succeeds.
	if code, _, _ := runCLI("init", "-dir", dir, "-force"); code != 0 {
		t.Errorf("init -force should overwrite")
	}
}

func TestClean(t *testing.T) {
	dir := t.TempDir()
	// clean operates on the configured output directory (default
	// internal/generated); place the fixtures there.
	outDir := filepath.Join(dir, "internal", "generated")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatal(err)
	}
	generated := filepath.Join(outDir, generatedFileName)
	handWritten := filepath.Join(outDir, "handwritten.go")
	unrelatedPrefixed := filepath.Join(outDir, generatedFilePrefix+"other.go")

	// A generated file carries the marker.
	if err := os.WriteFile(generated, []byte("// Code generated by goboot. DO NOT EDIT.\npackage x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// A hand-written file must never be removed.
	if err := os.WriteFile(handWritten, []byte("package x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// A file with the prefix but no marker must not be removed.
	if err := os.WriteFile(unrelatedPrefixed, []byte("package x\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	code, _, errOut := runCLI("clean", "-dir", dir)
	if code != 0 {
		t.Fatalf("clean exit = %d, stderr=%s", code, errOut)
	}
	if _, err := os.Stat(generated); !os.IsNotExist(err) {
		t.Errorf("generated file should have been removed")
	}
	if _, err := os.Stat(handWritten); err != nil {
		t.Errorf("hand-written file must not be removed")
	}
	if _, err := os.Stat(unrelatedPrefixed); err != nil {
		t.Errorf("prefixed file without the marker must not be removed")
	}
}

func TestDoctor(t *testing.T) {
	// Run against the module root, which has a go.mod.
	code, out, _ := runCLI("doctor", "-dir", "../..")
	if code != 0 {
		t.Fatalf("doctor exit = %d", code)
	}
	if !strings.Contains(out, "go.mod") || !strings.Contains(out, "go version") {
		t.Errorf("doctor output = %q", out)
	}
}

// TestGenerateEndToEnd is the acceptance scenario of §59: run `goboot generate`
// against annotated packages and confirm the generated code compiles.
func TestGenerateEndToEnd(t *testing.T) {
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	tmp, err := os.MkdirTemp(root, "gencli")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmp)

	outRel, err := filepath.Rel(root, tmp)
	if err != nil {
		t.Fatal(err)
	}

	code, out, errOut := runCLI("generate",
		"-dir", root,
		"-output", outRel,
		"-package", "wiring",
		"-verbose",
		"./compiler/testdata/diapp/...")
	if code != 0 {
		t.Fatalf("generate exit = %d\nstdout=%s\nstderr=%s", code, out, errOut)
	}

	target := filepath.Join(tmp, generatedFileName)
	if _, err := os.Stat(target); err != nil {
		t.Fatalf("generated file not written: %v", err)
	}

	// The generated package must compile (§59 step 5).
	cmd := exec.Command("go", "build", ".")
	cmd.Dir = tmp
	if buildOut, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated code does not compile: %v\n%s", err, buildOut)
	}
}

func TestGenerateCleanFlag(t *testing.T) {
	root, _ := filepath.Abs(filepath.Join("..", ".."))
	tmp, err := os.MkdirTemp(root, "gencli")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmp)
	outRel, _ := filepath.Rel(root, tmp)

	// A stale generated file that clean should remove before regenerating.
	stale := filepath.Join(tmp, generatedFilePrefix+"stale.gen.go")
	if err := os.WriteFile(stale, []byte("// Code generated by goboot. DO NOT EDIT.\npackage wiring\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	code, _, errOut := runCLI("generate",
		"-dir", root, "-output", outRel, "-package", "wiring", "-clean",
		"./compiler/testdata/diapp/...")
	if code != 0 {
		t.Fatalf("generate -clean exit = %d, stderr=%s", code, errOut)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Errorf("stale generated file should have been cleaned")
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func TestValidateWithProfile(t *testing.T) {
	// Without the profile, profile-gated components are excluded.
	_, outNo, _ := runCLI("validate", "-dir", compilerDir, "./testdata/conditions")
	// With the profile, more components are active.
	_, outProd, _ := runCLI("validate", "-dir", compilerDir, "-profile", "production", "./testdata/conditions")
	if outNo == outProd {
		t.Errorf("profile should change the active component set:\nno=%q\nprod=%q", outNo, outProd)
	}
	if !strings.Contains(outProd, "5 component") {
		t.Errorf("production profile should activate 5 components, got %q", outProd)
	}
	if !strings.Contains(outNo, "3 component") {
		t.Errorf("no profile should leave 3 components, got %q", outNo)
	}
}

func TestValidateWithProperty(t *testing.T) {
	_, out, _ := runCLI("validate", "-dir", compilerDir, "-property", "cache.enabled=true", "./testdata/conditions")
	if !strings.Contains(out, "4 component") {
		t.Errorf("cache.enabled=true should activate cacheEnabled (4 components), got %q", out)
	}
}
