// Code generated by goboot. DO NOT EDIT.

package authhttpe2e

import (
	"github.com/zombocoder/goboot/compiler/testdata/authhttpapp"
	"github.com/zombocoder/goboot/runtime"
	"net/http"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	SecretController *authhttpapp.SecretController
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents() (*Components, error) {
	secretController := authhttpapp.NewSecretController()

	return &Components{
		SecretController: secretController,
	}, nil
}

// makeSecretControllerGetHandler handles GET /secret.
func makeSecretControllerGetHandler(secretController *authhttpapp.SecretController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		principal, err := deps.Authenticator.Authenticate(ctx, r)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		ctx = runtime.WithPrincipal(ctx, principal)
		if err := deps.Authorizer.Authorize(ctx, runtime.AuthorizationRequest{
			Roles: []string{"user"},
			Mode:  runtime.AuthorizationModeAny,
		}); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := secretController.Get(ctx)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 200, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// RegisterRoutes registers every generated handler on the mux.
func RegisterRoutes(mux *http.ServeMux, components *Components, deps runtime.HTTPHandlerDependencies) {
	mux.HandleFunc("GET /secret", makeSecretControllerGetHandler(components.SecretController, deps))
}

// NewApplication builds the components and assembles a runnable application.
func NewApplication(deps runtime.HTTPHandlerDependencies, addr string) (*runtime.Application, error) {
	components, err := buildComponents()
	if err != nil {
		return nil, err
	}
	var lc *runtime.Lifecycle
	mux := http.NewServeMux()
	RegisterRoutes(mux, components, deps)
	server := &http.Server{Addr: addr, Handler: mux}
	return &runtime.Application{Server: server, Lifecycle: lc, Scheduler: nil}, nil
}
