// Code generated by goboot. DO NOT EDIT.

package schede2e

import (
	"context"
	"github.com/zombocoder/goboot/compiler/testdata/schedtick"
	"github.com/zombocoder/goboot/runtime"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Ticker *schedtick.Ticker
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents() (*Components, error) {
	ticker := schedtick.NewTicker()

	return &Components{
		Ticker: ticker,
	}, nil
}

// buildScheduler registers component @Scheduled tasks.
func buildScheduler(components *Components) *runtime.Scheduler {
	sched := runtime.NewScheduler()
	sched.Register(runtime.ScheduledTask{
		Name:     "ticker.Tick",
		Interval: 5000000,
		Run:      func(ctx context.Context) error { return components.Ticker.Tick(ctx) },
	})
	return sched
}

// NewApplication builds the components and assembles a runnable application.
func NewApplication() (*runtime.Application, error) {
	components, err := buildComponents()
	if err != nil {
		return nil, err
	}
	var lc *runtime.Lifecycle
	sched := buildScheduler(components)
	return &runtime.Application{Lifecycle: lc, Scheduler: sched}, nil
}
