// Code generated by goboot. DO NOT EDIT.

package advicee2e

import (
	"context"
	"errors"
	"github.com/zombocoder/goboot/compiler/testdata/adviceapp"
	"github.com/zombocoder/goboot/runtime"
	"net/http"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Advice  *adviceapp.Advice
	Handler *adviceapp.Handler
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents() (*Components, error) {
	advice := adviceapp.NewAdvice()
	handler := adviceapp.NewHandler()

	return &Components{
		Advice:  advice,
		Handler: handler,
	}, nil
}

// makeHandlerLookupHandler handles GET /things/{id}.
func makeHandlerLookupHandler(handler *adviceapp.Handler, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		var request adviceapp.LookupRequest
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := handler.Lookup(ctx, request)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 200, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// exceptionDispatcher routes controller errors to @ExceptionHandler methods,
// falling back to the delegate ErrorHandler when none match.
type exceptionDispatcher struct {
	components *Components
	delegate   runtime.ErrorHandler
	writer     runtime.ResponseWriter
}

// newExceptionDispatcher wraps deps.ErrorHandler with advice dispatch.
func newExceptionDispatcher(components *Components, deps runtime.HTTPHandlerDependencies) *exceptionDispatcher {
	return &exceptionDispatcher{components: components, delegate: deps.ErrorHandler, writer: deps.ResponseWriter}
}

func (d *exceptionDispatcher) Handle(ctx context.Context, w http.ResponseWriter, r *http.Request, err error) {
	var e0 *adviceapp.ConflictError
	if errors.As(err, &e0) {
		d.delegate.Handle(ctx, w, r, d.components.Advice.HandleConflict(ctx, e0))
		return
	}
	var e1 *adviceapp.NotFoundError
	if errors.As(err, &e1) {
		response, herr := d.components.Advice.HandleNotFound(ctx, e1)
		if herr != nil {
			d.delegate.Handle(ctx, w, r, herr)
			return
		}
		if werr := d.writer.Write(ctx, w, 404, response); werr != nil {
			d.delegate.Handle(ctx, w, r, werr)
		}
		return
	}
	d.delegate.Handle(ctx, w, r, d.components.Advice.HandleAny(ctx, err))
}

// RegisterRoutes registers every generated handler on the mux.
func RegisterRoutes(mux *http.ServeMux, components *Components, deps runtime.HTTPHandlerDependencies) {
	deps.ErrorHandler = newExceptionDispatcher(components, deps)
	mux.HandleFunc("GET /things/{id}", makeHandlerLookupHandler(components.Handler, deps))
}

// NewApplication builds the components and assembles a runnable application.
func NewApplication(deps runtime.HTTPHandlerDependencies, addr string) (*runtime.Application, error) {
	components, err := buildComponents()
	if err != nil {
		return nil, err
	}
	var lc *runtime.Lifecycle
	mux := http.NewServeMux()
	RegisterRoutes(mux, components, deps)
	server := &http.Server{Addr: addr, Handler: mux}
	return &runtime.Application{Server: server, Lifecycle: lc, Scheduler: nil}, nil
}
