// Code generated by goboot. DO NOT EDIT.

package authe2e

import (
	"context"
	"github.com/zombocoder/goboot/compiler/testdata/authapp"
	"github.com/zombocoder/goboot/runtime"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Admin             *authapp.AdminService
	AdminServiceProxy authapp.Admin
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents(proxyDeps runtime.ProxyDependencies) (*Components, error) {
	admin := authapp.NewAdminService()
	adminServiceProxy := NewAdminServiceProxy(admin, proxyDeps)

	return &Components{
		Admin:             admin,
		AdminServiceProxy: adminServiceProxy,
	}, nil
}

// AdminServiceProxy is the generated interception proxy for AdminService.
type AdminServiceProxy struct {
	target      *authapp.AdminService
	transaction runtime.TransactionManager
	tracer      runtime.Tracer
	metrics     runtime.MethodMetrics
	authorizer  runtime.Authorizer
}

// NewAdminServiceProxy builds the AdminServiceProxy.
func NewAdminServiceProxy(target *authapp.AdminService, deps runtime.ProxyDependencies) *AdminServiceProxy {
	return &AdminServiceProxy{target: target, transaction: deps.Transactions, tracer: deps.Tracer, metrics: deps.Metrics, authorizer: deps.Authorizer}
}

func (p *AdminServiceProxy) DeleteAll(a0 context.Context) (err error) {
	if err = p.authorizer.Authorize(a0, runtime.AuthorizationRequest{Roles: []string{"admin"}, Mode: runtime.AuthorizationModeAll}); err == nil {
		err = p.target.DeleteAll(a0)
	}
	return
}

func (p *AdminServiceProxy) Read(a0 context.Context) (r0 string, err error) {
	if err = p.authorizer.Authorize(a0, runtime.AuthorizationRequest{Roles: []string{"reader"}}); err == nil {
		r0, err = p.target.Read(a0)
	}
	return
}
