package cli

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// Self-bootstrap builds and caches a plugin-linked CLI from goboot.yaml, then
// re-execs it, so the stock `goboot` binary transparently gains the configured
// plugins without the developer maintaining a custom main (§46.2).

// cliImportPath is the importable CLI package a generated tool main injects into.
const cliImportPath = "github.com/zombocoder/goboot/cli"

// cacheDir is the per-project directory holding the generated tool main and the
// built plugin-aware binaries. Its leading dot keeps it out of `go build ./...`
// and `go test ./...`, and a self-written .gitignore keeps it out of version
// control.
const cacheDir = ".goboot"

// bootstrapEnv, when set to "off", disables the self-bootstrap. The re-exec sets
// it on the child, and a developer can set it to force the plugin-free binary.
const bootstrapEnv = "GOBOOT_BOOTSTRAP"

// maybeBootstrap builds (or reuses) a plugin-aware CLI for the configured
// plugins and re-execs it, returning its exit code and true. It returns
// (0, false) when no bootstrap is needed: this binary already links plugins, the
// bootstrap is disabled, or goboot.yaml lists none.
func maybeBootstrap(dir string, cfg projectConfig, stdout, stderr io.Writer) (int, bool) {
	if len(hostPlugins) > 0 || os.Getenv(bootstrapEnv) == "off" || len(cfg.Plugins) == 0 {
		return 0, false
	}
	bin, err := ensurePluginBinary(dir, cfg, stderr)
	if err != nil {
		fmt.Fprintf(stderr, "goboot: plugin bootstrap failed: %v\n", err)
		return 1, true
	}
	cmd := exec.Command(bin, os.Args[1:]...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	cmd.Env = append(os.Environ(), bootstrapEnv+"=off")
	if err := cmd.Run(); err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return ee.ExitCode(), true
		}
		fmt.Fprintf(stderr, "goboot: %v\n", err)
		return 1, true
	}
	return 0, true
}

// ensurePluginBinary returns the path to a plugin-aware CLI for cfg, building and
// caching it on first use. The cache key covers the plugin set and toolchain, so
// a changed goboot.yaml transparently triggers a rebuild.
func ensurePluginBinary(dir string, cfg projectConfig, stderr io.Writer) (string, error) {
	refs := normalizedPluginRefs(cfg)
	key := bootstrapKey(refs)
	binDir := filepath.Join(dir, cacheDir, "bin")
	binPath := filepath.Join(binDir, "goboot-"+key+exeSuffix())
	if _, err := os.Stat(binPath); err == nil {
		return binPath, nil
	}

	toolDir := filepath.Join(dir, cacheDir, "tool")
	if err := os.MkdirAll(toolDir, 0o755); err != nil {
		return "", err
	}
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return "", err
	}
	if err := writeGitignore(filepath.Join(dir, cacheDir)); err != nil {
		return "", err
	}

	src, err := toolMain(refs)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(toolDir, "main.go"), []byte(src), 0o644); err != nil {
		return "", err
	}

	fmt.Fprintf(stderr, "goboot: building plugin-aware CLI (%s)…\n", pluginSummary(refs))
	pkg := "./" + filepath.ToSlash(filepath.Join(cacheDir, "tool"))
	if out, err := goBuild(dir, binPath, pkg); err != nil {
		// The plugin modules may not be in go.mod yet; resolve and retry once.
		goGetPlugins(dir, refs, stderr)
		if out2, err2 := goBuild(dir, binPath, pkg); err2 != nil {
			return "", fmt.Errorf("building plugin CLI:\n%s%s", out, out2)
		}
	}
	return binPath, nil
}

// bootstrapKey hashes the plugin set and toolchain into a short cache key.
func bootstrapKey(refs []pluginRef) string {
	h := sha256.New()
	fmt.Fprintln(h, runtime.Version())
	fmt.Fprintln(h, CLIVersion)
	for _, r := range refs {
		fmt.Fprintf(h, "%s@%s|%s|%s\n", r.Module, r.Version, r.Import, r.New)
	}
	return hex.EncodeToString(h.Sum(nil))[:12]
}

// toolMain renders a main package that injects the plugin refs into cli.Main.
// Output is gofmt-normalized so it is stable and readable.
func toolMain(refs []pluginRef) (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by goboot. DO NOT EDIT.\n")
	b.WriteString("// Plugin-aware goboot CLI built from goboot.yaml.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"os\"\n\n")
	fmt.Fprintf(&b, "\t%q\n", cliImportPath)
	for i, r := range refs {
		fmt.Fprintf(&b, "\tp%d %q\n", i, r.Import)
	}
	b.WriteString(")\n\n")
	b.WriteString("func main() {\n")
	b.WriteString("\tos.Exit(cli.Main(\n")
	for i, r := range refs {
		fmt.Fprintf(&b, "\t\tp%d.%s(),\n", i, r.New)
	}
	b.WriteString("\t))\n}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("formatting generated tool main: %w", err)
	}
	return string(formatted), nil
}

// normalizedPluginRefs returns the configured plugin refs with defaults applied,
// ordered deterministically by import path.
func normalizedPluginRefs(cfg projectConfig) []pluginRef {
	refs := make([]pluginRef, 0, len(cfg.Plugins))
	for _, r := range cfg.Plugins {
		refs = append(refs, r.normalize())
	}
	sort.Slice(refs, func(i, j int) bool {
		if refs[i].Import != refs[j].Import {
			return refs[i].Import < refs[j].Import
		}
		return refs[i].New < refs[j].New
	})
	return refs
}

// goBuild compiles the tool package into binPath, running in dir so the project
// go.mod resolves both goboot and the plugin modules. It uses -mod=mod so the
// build can add the plugin's transitive requires to go.mod on first use rather
// than failing under the default readonly mode.
func goBuild(dir, binPath, pkg string) (string, error) {
	cmd := exec.Command("go", "build", "-mod=mod", "-o", binPath, pkg)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), err
}

// goGetPlugins best-effort adds each plugin module to go.mod at its pinned
// version. Failures are reported but not fatal — the retry build surfaces the
// real error, and a project using replace directives needs no fetch.
func goGetPlugins(dir string, refs []pluginRef, stderr io.Writer) {
	for _, r := range refs {
		spec := r.Module
		if r.Version != "" {
			spec += "@" + r.Version
		}
		cmd := exec.Command("go", "get", spec)
		cmd.Dir = dir
		if out, err := cmd.CombinedOutput(); err != nil {
			fmt.Fprintf(stderr, "goboot: go get %s: %v\n%s", spec, err, out)
		}
	}
}

// pluginSummary is a compact human description of the plugin set.
func pluginSummary(refs []pluginRef) string {
	parts := make([]string, len(refs))
	for i, r := range refs {
		v := r.Version
		if v == "" {
			v = "latest"
		}
		parts[i] = r.Module + "@" + v
	}
	return strings.Join(parts, ", ")
}

// writeGitignore makes the cache directory self-ignoring.
func writeGitignore(dir string) error {
	path := filepath.Join(dir, ".gitignore")
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return os.WriteFile(path, []byte("# goboot plugin build cache\n*\n"), 0o644)
}

// exeSuffix is the platform executable suffix.
func exeSuffix() string {
	if runtime.GOOS == "windows" {
		return ".exe"
	}
	return ""
}
