// Code generated by goboot. DO NOT EDIT.

package verbe2e

import (
	"github.com/zombocoder/goboot/compiler/testdata/verbapp"
	"github.com/zombocoder/goboot/runtime"
	"net/http"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	WidgetController *verbapp.WidgetController
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents() (*Components, error) {
	widgetController := verbapp.NewWidgetController()

	return &Components{
		WidgetController: widgetController,
	}, nil
}

// makeWidgetControllerCreateWidgetHandler handles POST /widgets.
func makeWidgetControllerCreateWidgetHandler(widgetController *verbapp.WidgetController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		var request verbapp.NameRequest
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := widgetController.CreateWidget(ctx, request)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 201, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// makeWidgetControllerDeleteWidgetHandler handles DELETE /widgets/{id}.
func makeWidgetControllerDeleteWidgetHandler(widgetController *verbapp.WidgetController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		var request verbapp.IDRequest
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := widgetController.DeleteWidget(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 204, nil); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// makeWidgetControllerGetWidgetHandler handles GET /widgets/{id}.
func makeWidgetControllerGetWidgetHandler(widgetController *verbapp.WidgetController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		var request verbapp.IDRequest
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := widgetController.GetWidget(ctx, request)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 200, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// makeWidgetControllerPatchWidgetHandler handles PATCH /widgets/{id}.
func makeWidgetControllerPatchWidgetHandler(widgetController *verbapp.WidgetController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		var request verbapp.UpdateRequest
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := widgetController.PatchWidget(ctx, request)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 200, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// makeWidgetControllerReplaceWidgetHandler handles PUT /widgets/{id}.
func makeWidgetControllerReplaceWidgetHandler(widgetController *verbapp.WidgetController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		var request verbapp.UpdateRequest
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := widgetController.ReplaceWidget(ctx, request)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 200, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// RegisterRoutes registers every generated handler on the mux.
func RegisterRoutes(mux *http.ServeMux, components *Components, deps runtime.HTTPHandlerDependencies) {
	mux.HandleFunc("POST /widgets", makeWidgetControllerCreateWidgetHandler(components.WidgetController, deps))
	mux.HandleFunc("DELETE /widgets/{id}", makeWidgetControllerDeleteWidgetHandler(components.WidgetController, deps))
	mux.HandleFunc("GET /widgets/{id}", makeWidgetControllerGetWidgetHandler(components.WidgetController, deps))
	mux.HandleFunc("PATCH /widgets/{id}", makeWidgetControllerPatchWidgetHandler(components.WidgetController, deps))
	mux.HandleFunc("PUT /widgets/{id}", makeWidgetControllerReplaceWidgetHandler(components.WidgetController, deps))
}

// NewApplication builds the components and assembles a runnable application.
func NewApplication(deps runtime.HTTPHandlerDependencies, addr string) (*runtime.Application, error) {
	components, err := buildComponents()
	if err != nil {
		return nil, err
	}
	var lc *runtime.Lifecycle
	mux := http.NewServeMux()
	RegisterRoutes(mux, components, deps)
	server := &http.Server{Addr: addr, Handler: mux}
	return &runtime.Application{Server: server, Lifecycle: lc, Scheduler: nil}, nil
}
