// Package di generates the dependency-injection wiring for an application: a
// single Go source file that constructs every singleton component in dependency
// order and returns them (§32). The output is ordinary, readable Go — no custom
// runtime, no reflection — carrying the generated-code marker (§6.3) and is
// deterministic for a given model (§6.7).
package di

import (
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strings"
	"unicode"

	"github.com/zombocoder/goboot/graph"
	"github.com/zombocoder/goboot/model"
)

// GeneratedMarker is the line that identifies goboot-generated files (§6.3).
const GeneratedMarker = "// Code generated by goboot. DO NOT EDIT."

// Options configures wiring generation.
type Options struct {
	// Package is the name of the package the file is generated into.
	Package string
	// SelfPath is the import path of the generated package; references to it are
	// left unqualified. It may be empty.
	SelfPath string
}

// binding pairs a component with the local variable and struct field names the
// generator assigns it.
type binding struct {
	comp  *model.Component
	local string // local variable name inside buildComponents
	field string // exported field name on the Components struct
}

// Generate produces the wiring source for the application. It returns an error
// if the graph contains a cycle or a dependency is unresolved, since neither can
// produce compilable output.
func Generate(app *model.Application, g *graph.Graph, opts Options) (string, error) {
	order, cyc := g.ConstructionOrder()
	if cyc != nil {
		return "", fmt.Errorf("di: cannot generate wiring for a graph with a dependency cycle")
	}
	if opts.Package == "" {
		opts.Package = "generated"
	}

	feats := detectFeatures(app)

	// Register every import up front so that local variable names can be kept
	// clear of package aliases (a local named "config" would otherwise shadow
	// an imported "config" package).
	im := newImports(opts.SelfPath)
	for _, id := range order {
		registerImports(g.Component(id), im)
	}
	registerRouteImports(app, im)
	if feats.hasConfig {
		im.add(configPath, "config")
	}
	if feats.hasProxies {
		im.add(runtimePath, "runtime")
	}
	reserved := map[string]bool{"err": true, "out": true}
	if feats.hasConfig {
		reserved["configSource"] = true
	}
	if feats.hasProxies {
		reserved["proxyDeps"] = true
	}
	for _, alias := range im.aliases() {
		reserved[alias] = true
	}

	bindings, byID := assignNames(order, g, reserved)

	body, err := renderConstructors(bindings, byID, im)
	if err != nil {
		return "", err
	}

	sec := sections{
		pkg:           opts.Package,
		buildParam:    buildComponentsParam(feats, im),
		structDef:     renderStruct(bindings, im),
		body:          body,
		returnStmt:    renderReturn(bindings),
		configLoaders: renderConfigLoaders(app, im),
		proxyPart:     renderProxies(app, byID, im),
		httpPart:      renderHTTP(app, byID, im),
		lifecyclePart: renderLifecycle(app, bindings, byID, im, feats),
		appPart:       renderApplication(app, im, feats),
	}
	src := assemble(sec, im)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return "", fmt.Errorf("di: formatting generated source: %w\n%s", err, src)
	}
	return string(formatted), nil
}

// assignNames allocates a unique local and field name for each component,
// following construction order so names are stable. It returns the bindings in
// order and an index by component ID.
func assignNames(order []model.ComponentID, g *graph.Graph, reserved map[string]bool) ([]*binding, map[model.ComponentID]*binding) {
	bindings := make([]*binding, 0, len(order))
	byID := make(map[model.ComponentID]*binding, len(order))
	usedLocal := map[string]bool{}
	for name := range reserved {
		usedLocal[name] = true
	}
	usedField := map[string]bool{}

	for _, id := range order {
		c := g.Component(id)
		if c == nil {
			continue
		}
		local := unique(toLocalName(c.Name), usedLocal)
		field := unique(toFieldName(c.Name), usedField)
		b := &binding{comp: c, local: local, field: field}
		bindings = append(bindings, b)
		byID[id] = b
	}
	return bindings, byID
}

// registerImports pre-registers every package a component contributes: its
// provided type, its constructor's package, and fmt when the constructor can
// return an error.
func registerImports(c *model.Component, im *imports) {
	if c == nil {
		return
	}
	if c.ProvidedType != nil {
		renderType(c.ProvidedType, im)
	}
	if c.Constructor != nil {
		im.add(c.Constructor.PackagePath, c.Constructor.PackageName)
		if c.Constructor.ReturnsError {
			im.add("fmt", "fmt")
		}
	}
}

// renderConstructors emits the assignment statements that build each component
// in order.
func renderConstructors(bindings []*binding, byID map[model.ComponentID]*binding, im *imports) (string, error) {
	var b strings.Builder
	for _, bd := range bindings {
		stmt, err := renderConstructor(bd, byID, im)
		if err != nil {
			return "", err
		}
		b.WriteString(stmt)
	}
	return b.String(), nil
}

// renderConstructor emits the statement(s) constructing a single component.
func renderConstructor(bd *binding, byID map[model.ComponentID]*binding, im *imports) (string, error) {
	c := bd.comp
	ctor := c.Constructor

	if ctor != nil && ctor.Constructorless {
		typeName := c.Named.Obj().Name()
		ref := im.qualify(ctor.PackagePath, ctor.PackageName, typeName)
		return fmt.Sprintf("\t%s := &%s{}\n", bd.local, ref), nil
	}

	// A configuration-properties component is loaded from the config source by
	// a generated loader that lives in this package (so it is unqualified).
	if ctor != nil && ctor.ConfigLoader {
		im.add("fmt", "fmt")
		return fmt.Sprintf(
			"\t%s, err := %s(configSource)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n",
			bd.local, ctor.FuncName), nil
	}

	// A proxy wraps its already-constructed target with the proxy dependencies
	// bundle. Its constructor is generated locally in this package.
	if c.Kind == model.ComponentProxy {
		targetBinding, ok := byID[c.ProxyTarget]
		if !ok {
			return "", fmt.Errorf("di: proxy %s has no constructed target %s", c.Name, c.ProxyTarget)
		}
		return fmt.Sprintf("\t%s := %s(%s, proxyDeps)\n", bd.local, ctor.FuncName, targetBinding.local), nil
	}

	args, err := constructorArgs(c, byID)
	if err != nil {
		return "", err
	}
	call := fmt.Sprintf("%s(%s)",
		im.qualify(ctor.PackagePath, ctor.PackageName, ctor.FuncName),
		strings.Join(args, ", "))

	if ctor.ReturnsError {
		im.add("fmt", "fmt")
		return fmt.Sprintf(
			"\t%s, err := %s\n\tif err != nil {\n\t\treturn nil, fmt.Errorf(%q, err)\n\t}\n",
			bd.local, call, "construct "+c.Name+": %w"), nil
	}
	return fmt.Sprintf("\t%s := %s\n", bd.local, call), nil
}

// constructorArgs renders the argument list for a component's constructor by
// looking up each resolved dependency's local variable.
func constructorArgs(c *model.Component, byID map[model.ComponentID]*binding) ([]string, error) {
	args := make([]string, 0, len(c.Dependencies))
	for _, dep := range c.Dependencies {
		if dep.ResolvedTo == "" {
			return nil, fmt.Errorf("di: dependency %q of %s is unresolved", dep.Name, c.Name)
		}
		b, ok := byID[dep.ResolvedTo]
		if !ok {
			return nil, fmt.Errorf("di: dependency %q of %s resolves to unknown component %s",
				dep.Name, c.Name, dep.ResolvedTo)
		}
		args = append(args, b.local)
	}
	return args, nil
}

// renderStruct emits the Components struct, with one field per component sorted
// by field name for deterministic output.
func renderStruct(bindings []*binding, im *imports) string {
	sorted := append([]*binding(nil), bindings...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].field < sorted[j].field })

	var b strings.Builder
	b.WriteString("// Components holds the constructed singleton components of the application.\n")
	b.WriteString("type Components struct {\n")
	for _, bd := range sorted {
		typ := renderType(bd.comp.ProvidedType, im)
		b.WriteString(fmt.Sprintf("\t%s %s\n", bd.field, typ))
	}
	b.WriteString("}\n")
	return b.String()
}

// renderReturn emits the &Components{...} literal returned by buildComponents.
func renderReturn(bindings []*binding) string {
	sorted := append([]*binding(nil), bindings...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].field < sorted[j].field })

	var b strings.Builder
	b.WriteString("\treturn &Components{\n")
	for _, bd := range sorted {
		b.WriteString(fmt.Sprintf("\t\t%s: %s,\n", bd.field, bd.local))
	}
	b.WriteString("\t}, nil\n")
	return b.String()
}

// sections holds the rendered pieces of the generated file. Import registration
// happens while rendering each piece, so assemble must run after they are built.
type sections struct {
	pkg           string
	buildParam    string // parameter list for buildComponents (e.g. config source)
	structDef     string
	body          string
	returnStmt    string
	configLoaders string
	proxyPart     string
	httpPart      string
	lifecyclePart string
	appPart       string
}

// assemble stitches the file together and returns unformatted source.
func assemble(sec sections, im *imports) string {
	var b strings.Builder
	b.WriteString(GeneratedMarker + "\n\n")
	b.WriteString("package " + sec.pkg + "\n\n")
	if block := im.block(); block != "" {
		b.WriteString(block + "\n")
	}
	b.WriteString(sec.structDef + "\n")
	b.WriteString("// buildComponents constructs every singleton component in dependency order.\n")
	fmt.Fprintf(&b, "func buildComponents(%s) (*Components, error) {\n", sec.buildParam)
	b.WriteString(sec.body)
	if sec.body != "" {
		b.WriteString("\n")
	}
	b.WriteString(sec.returnStmt)
	b.WriteString("}\n")
	for _, part := range []string{sec.configLoaders, sec.proxyPart, sec.httpPart, sec.lifecyclePart, sec.appPart} {
		if part != "" {
			b.WriteString("\n")
			b.WriteString(part)
		}
	}
	return b.String()
}

// renderType renders a component's provided type, registering its imports.
func renderType(t types.Type, im *imports) string {
	return types.TypeString(t, im.qualifier())
}

// toLocalName derives a lowerCamel local variable name from a component name.
func toLocalName(name string) string {
	id := sanitizeIdent(name)
	if id == "" {
		return "component"
	}
	r := []rune(id)
	r[0] = unicode.ToLower(r[0])
	return avoidKeyword(string(r))
}

// toFieldName derives an exported field name from a component name.
func toFieldName(name string) string {
	id := sanitizeIdent(name)
	if id == "" {
		return "Component"
	}
	r := []rune(id)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

// sanitizeIdent strips characters that are not valid in a Go identifier and
// ensures the result begins with a letter.
func sanitizeIdent(name string) string {
	var b strings.Builder
	for i, r := range name {
		switch {
		case unicode.IsLetter(r) || r == '_':
			b.WriteRune(r)
		case unicode.IsDigit(r) && i > 0:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// unique returns candidate, appending a numeric suffix until it is unused, and
// records it as used.
func unique(candidate string, used map[string]bool) string {
	name := candidate
	for i := 2; used[name]; i++ {
		name = fmt.Sprintf("%s%d", candidate, i)
	}
	used[name] = true
	return name
}

// avoidKeyword suffixes an underscore when name collides with a Go keyword.
func avoidKeyword(name string) string {
	if goKeywords[name] {
		return name + "_"
	}
	return name
}

var goKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
}
