// Code generated by goboot. DO NOT EDIT.

package repoe2e

import (
	"context"
	"github.com/zombocoder/goboot/compiler/testdata/repoapp"
	"github.com/zombocoder/goboot/runtime/db"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	UserRepository repoapp.UserRepository
	UserService    *repoapp.UserService
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents(dbProvider db.DBProvider) (*Components, error) {
	userRepository := NewUserRepositoryImpl(dbProvider)
	userService := repoapp.NewUserService(userRepository)

	return &Components{
		UserRepository: userRepository,
		UserService:    userService,
	}, nil
}

// UserRepositoryImpl is the generated implementation of UserRepository.
type UserRepositoryImpl struct {
	db db.DBProvider
}

// NewUserRepositoryImpl builds the repository.
func NewUserRepositoryImpl(db db.DBProvider) *UserRepositoryImpl {
	return &UserRepositoryImpl{db: db}
}

func (r *UserRepositoryImpl) Count(a0 context.Context) (int64, error) {
	var v int64
	if err := r.db.DB(a0).QueryRowContext(a0, `SELECT count(*) FROM users`).Scan(&v); err != nil {
		return 0, err
	}
	return v, nil
}

func (r *UserRepositoryImpl) Create(a0 context.Context, a1 string, a2 string, a3 string) error {
	_, err := r.db.DB(a0).ExecContext(a0, `INSERT INTO users (id, name, email) VALUES ($1, $2, $3)`, a1, a2, a3)
	return err
}

func (r *UserRepositoryImpl) Delete(a0 context.Context, a1 string) (int64, error) {
	res, err := r.db.DB(a0).ExecContext(a0, `DELETE FROM users WHERE id = $1`, a1)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

func (r *UserRepositoryImpl) FindAll(a0 context.Context) ([]*repoapp.User, error) {
	rows, err := r.db.DB(a0).QueryContext(a0, `SELECT id, name, email FROM users`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*repoapp.User
	for rows.Next() {
		var e repoapp.User
		if err := rows.Scan(&e.ID, &e.Name, &e.Email); err != nil {
			return nil, err
		}
		out = append(out, &e)
	}
	return out, rows.Err()
}

func (r *UserRepositoryImpl) FindByID(a0 context.Context, a1 string) (*repoapp.User, error) {
	var e repoapp.User
	if err := r.db.DB(a0).QueryRowContext(a0, `SELECT id, name, email FROM users WHERE id = $1`, a1).Scan(&e.ID, &e.Name, &e.Email); err != nil {
		return nil, err
	}
	return &e, nil
}
