// Code generated by goboot. DO NOT EDIT.

package batche2e

import (
	"context"
	"github.com/zombocoder/goboot/compiler/testdata/batchapp"
	"github.com/zombocoder/goboot/runtime/db"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	UserRepository batchapp.UserRepository
	UserService    *batchapp.UserService
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents(dbProvider db.DBProvider) (*Components, error) {
	userRepository := NewUserRepositoryImpl(dbProvider)
	userService := batchapp.NewUserService(userRepository)

	return &Components{
		UserRepository: userRepository,
		UserService:    userService,
	}, nil
}

// UserRepositoryImpl is the generated implementation of UserRepository.
type UserRepositoryImpl struct {
	db db.DBProvider
}

// NewUserRepositoryImpl builds the repository.
func NewUserRepositoryImpl(db db.DBProvider) *UserRepositoryImpl {
	return &UserRepositoryImpl{db: db}
}

func (r *UserRepositoryImpl) InsertAll(a0 context.Context, a1 []batchapp.User) (int64, error) {
	var affected int64
	for _, item := range a1 {
		res, err := r.db.DB(a0).ExecContext(a0, `INSERT INTO users (id, name) VALUES ($1, $2)`, item.ID, item.Name)
		if err != nil {
			return affected, err
		}
		n, err := res.RowsAffected()
		if err != nil {
			return affected, err
		}
		affected += n
	}
	return affected, nil
}

func (r *UserRepositoryImpl) Reindex(a0 context.Context) error {
	_, err := r.db.DB(a0).ExecContext(a0, `CALL reindex_users()`)
	return err
}

func (r *UserRepositoryImpl) TopByScore(a0 context.Context, a1 int64) ([]*batchapp.User, error) {
	rows, err := r.db.DB(a0).QueryContext(a0, `SELECT id, name FROM top_users($1)`, a1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*batchapp.User
	for rows.Next() {
		var e batchapp.User
		if err := rows.Scan(&e.ID, &e.Name); err != nil {
			return nil, err
		}
		out = append(out, &e)
	}
	return out, rows.Err()
}

func (r *UserRepositoryImpl) TouchAll(a0 context.Context, a1 string, a2 []string) error {
	for _, item := range a2 {
		if _, err := r.db.DB(a0).ExecContext(a0, `UPDATE users SET org = $1 WHERE id = $2`, a1, item); err != nil {
			return err
		}
	}
	return nil
}
