package metrics

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/zombocoder/goboot/annotation"
	"github.com/zombocoder/goboot/generator/di"
	"github.com/zombocoder/goboot/model"
	"github.com/zombocoder/goboot/plugin"
)

// promImport is the Prometheus client package the generated code depends on; the
// target module must require it.
const promImport = "github.com/prometheus/client_golang/prometheus"

// Analyze validates the @Counter/@Gauge annotations (names, labels, duplicates).
func (*Plugin) Analyze(app *model.Application) []*annotation.Diagnostic {
	_, diags := resolve(app)
	return diags
}

// Generate emits the Prometheus collectors, a RegisterMetrics function, and a
// typed accessor per metric (§46.1). It emits nothing when no metric is declared.
func (*Plugin) Generate(app *model.Application) ([]plugin.File, error) {
	metrics, _ := resolve(app) // diagnostics surface via Analyze
	if len(metrics) == 0 {
		return nil, nil
	}
	src, err := render(app, metrics)
	if err != nil {
		return nil, fmt.Errorf("metrics: %w", err)
	}
	return []plugin.File{{Name: outputFile, Content: src}}, nil
}

// render builds and gofmt-formats the metrics source.
func render(app *model.Application, metrics []metric) ([]byte, error) {
	pkg := app.Package
	if pkg == "" {
		pkg = "generated"
	}

	var b strings.Builder
	b.WriteString(di.GeneratedMarker + "\n")
	b.WriteString("// Prometheus collectors generated by the goboot metrics plugin from\n")
	b.WriteString("// @Counter / @Gauge annotations.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import %q\n\n", promImport)

	b.WriteString("var (\n")
	for _, m := range metrics {
		fmt.Fprintf(&b, "\t%s = %s\n", m.varName, collectorExpr(m))
	}
	b.WriteString(")\n\n")

	b.WriteString("// RegisterMetrics registers every @Counter/@Gauge collector with reg\n")
	b.WriteString("// (e.g. a *prometheus.Registry or prometheus.DefaultRegisterer).\n")
	b.WriteString("func RegisterMetrics(reg prometheus.Registerer) {\n\treg.MustRegister(\n")
	for _, m := range metrics {
		fmt.Fprintf(&b, "\t\t%s,\n", m.varName)
	}
	b.WriteString("\t)\n}\n\n")

	for _, m := range metrics {
		fmt.Fprintf(&b, "// %s returns the registered %q %s.\n", m.accessor, m.fullName, kindWord(m.kind))
		fmt.Fprintf(&b, "func %s() %s { return %s }\n\n", m.accessor, accessorType(m), m.varName)
	}

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w\n%s", err, b.String())
	}
	return out, nil
}

// collectorExpr renders the prometheus.New… constructor for a metric.
func collectorExpr(m metric) string {
	optsType, ctor, ctorVec := "CounterOpts", "NewCounter", "NewCounterVec"
	if m.kind == gaugeKind {
		optsType, ctor, ctorVec = "GaugeOpts", "NewGauge", "NewGaugeVec"
	}
	var opts strings.Builder
	fmt.Fprintf(&opts, "prometheus.%s{", optsType)
	if m.namespace != "" {
		fmt.Fprintf(&opts, "Namespace: %s, ", strconv.Quote(m.namespace))
	}
	fmt.Fprintf(&opts, "Name: %s, Help: %s}", strconv.Quote(m.name), strconv.Quote(m.help))

	if len(m.labels) == 0 {
		return fmt.Sprintf("prometheus.%s(%s)", ctor, opts.String())
	}
	return fmt.Sprintf("prometheus.%s(%s, %s)", ctorVec, opts.String(), stringSliceLit(m.labels))
}

// accessorType is the Go return type of a metric's accessor.
func accessorType(m metric) string {
	vec := len(m.labels) > 0
	switch {
	case m.kind == counterKind && vec:
		return "*prometheus.CounterVec"
	case m.kind == counterKind:
		return "prometheus.Counter"
	case m.kind == gaugeKind && vec:
		return "*prometheus.GaugeVec"
	default:
		return "prometheus.Gauge"
	}
}

func kindWord(k metricKind) string {
	if k == gaugeKind {
		return "gauge"
	}
	return "counter"
}

func stringSliceLit(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = strconv.Quote(s)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}
