// Code generated by goboot. DO NOT EDIT.

package gatee2e

import (
	"context"
	"github.com/zombocoder/goboot/compiler/testdata/gateapp"
	"github.com/zombocoder/goboot/runtime"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Downstream             *gateapp.DownstreamService
	DownstreamServiceProxy gateapp.Downstream
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents(proxyDeps runtime.ProxyDependencies) (*Components, error) {
	downstream := gateapp.NewDownstreamService()
	downstreamServiceProxy := NewDownstreamServiceProxy(downstream, proxyDeps)

	return &Components{
		Downstream:             downstream,
		DownstreamServiceProxy: downstreamServiceProxy,
	}, nil
}

// DownstreamServiceProxy is the generated interception proxy for DownstreamService.
type DownstreamServiceProxy struct {
	target       *gateapp.DownstreamService
	transaction  runtime.TransactionManager
	tracer       runtime.Tracer
	metrics      runtime.MethodMetrics
	authorizer   runtime.Authorizer
	logger       runtime.MethodLogger
	audit        runtime.AuditSink
	breakers     runtime.CircuitBreakerProvider
	rateLimiters runtime.RateLimiterProvider
	bulkheads    runtime.BulkheadProvider
}

// NewDownstreamServiceProxy builds the DownstreamServiceProxy.
func NewDownstreamServiceProxy(target *gateapp.DownstreamService, deps runtime.ProxyDependencies) *DownstreamServiceProxy {
	return &DownstreamServiceProxy{target: target, transaction: deps.Transactions, tracer: deps.Tracer, metrics: deps.Metrics, authorizer: deps.Authorizer, logger: deps.Logger, audit: deps.Audit, breakers: deps.Breakers, rateLimiters: deps.RateLimiters, bulkheads: deps.Bulkheads}
}

func (p *DownstreamServiceProxy) Bounded(a0 context.Context) (err error) {
	err = p.bulkheads.Bulkhead(runtime.BulkheadSpec{Name: "DownstreamService.Bounded", MaxConcurrent: 1}).Execute(a0, func(ctx context.Context) error {
		return p.target.Bounded(ctx)
	})
	return
}

func (p *DownstreamServiceProxy) Call(a0 context.Context) (err error) {
	err = p.breakers.CircuitBreaker(runtime.CircuitBreakerSpec{Name: "downstream", FailureThreshold: 2, ResetTimeout: 50000000}).Execute(a0, func(ctx context.Context) error {
		return p.target.Call(ctx)
	})
	return
}

func (p *DownstreamServiceProxy) Fetch(a0 context.Context) (r0 string, err error) {
	err = p.rateLimiters.RateLimiter(runtime.RateLimitSpec{Name: "DownstreamService.Fetch", Limit: 2, Period: 1000000000}).Execute(a0, func(ctx context.Context) error {
		var e error
		r0, e = p.target.Fetch(ctx)
		return e
	})
	return
}
