// Code generated by goboot. DO NOT EDIT.

package obse2e

import (
	"context"
	"github.com/zombocoder/goboot/compiler/testdata/obsapp"
	"github.com/zombocoder/goboot/runtime"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Vault             *obsapp.VaultService
	VaultServiceProxy obsapp.Vault
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents(proxyDeps runtime.ProxyDependencies) (*Components, error) {
	vault := obsapp.NewVaultService()
	vaultServiceProxy := NewVaultServiceProxy(vault, proxyDeps)

	return &Components{
		Vault:             vault,
		VaultServiceProxy: vaultServiceProxy,
	}, nil
}

// VaultServiceProxy is the generated interception proxy for VaultService.
type VaultServiceProxy struct {
	target       *obsapp.VaultService
	transaction  runtime.TransactionManager
	tracer       runtime.Tracer
	metrics      runtime.MethodMetrics
	authorizer   runtime.Authorizer
	logger       runtime.MethodLogger
	audit        runtime.AuditSink
	breakers     runtime.CircuitBreakerProvider
	rateLimiters runtime.RateLimiterProvider
	bulkheads    runtime.BulkheadProvider
}

// NewVaultServiceProxy builds the VaultServiceProxy.
func NewVaultServiceProxy(target *obsapp.VaultService, deps runtime.ProxyDependencies) *VaultServiceProxy {
	return &VaultServiceProxy{target: target, transaction: deps.Transactions, tracer: deps.Tracer, metrics: deps.Metrics, authorizer: deps.Authorizer, logger: deps.Logger, audit: deps.Audit, breakers: deps.Breakers, rateLimiters: deps.RateLimiters, bulkheads: deps.Bulkheads}
}

func (p *VaultServiceProxy) Rotate(a0 context.Context) (r0 string, err error) {
	logDone := p.logger.Log(a0, "VaultService.Rotate", "info")
	defer func() { logDone(err) }()
	r0, err = p.target.Rotate(a0)
	return
}

func (p *VaultServiceProxy) Store(a0 context.Context, a1 string) (err error) {
	logDone := p.logger.Log(a0, "VaultService.Store", "debug")
	defer func() { logDone(err) }()
	defer func() {
		p.audit.Record(a0, runtime.AuditEvent{Method: "VaultService.Store", Action: "store", Resource: "secret"}, err)
	}()
	err = p.target.Store(a0, a1)
	return
}
