package validate

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/zombocoder/goboot/generator/di"
	"github.com/zombocoder/goboot/model"
	"github.com/zombocoder/goboot/plugin"
)

const runtimeImport = "github.com/zombocoder/goboot/runtime"

// emailPattern is the regex backing @Email. It is intentionally permissive —
// enough to catch obvious mistakes without rejecting valid, unusual addresses.
const emailPattern = `^[^@\s]+@[^@\s]+\.[^@\s]+$`

// Generate emits the request validator from the resolved constraints (§46.1).
// It emits nothing when no request field carries a constraint. Diagnostics are
// surfaced by Analyze, so Generate only renders the enforceable rules.
func (*Plugin) Generate(app *model.Application) ([]plugin.File, error) {
	rules, _ := resolve(app)
	if len(rules) == 0 {
		return nil, nil
	}
	src, err := render(app, rules)
	if err != nil {
		return nil, fmt.Errorf("validate: %w", err)
	}
	return []plugin.File{{Name: outputFile, Content: src}}, nil
}

// render builds and gofmt-formats the validator source.
func render(app *model.Application, rules []structRules) ([]byte, error) {
	pkg := app.Package
	if pkg == "" {
		pkg = "generated" // defensive; the generate command always sets Package
	}

	needUTF8, needRegexp, needEmail := scanNeeds(rules)

	var b strings.Builder
	b.WriteString(di.GeneratedMarker + "\n")
	b.WriteString("// Request validator generated by the goboot validate plugin from\n")
	b.WriteString("// @Required/@Min/@Max/@Size/@Pattern/@Email field annotations.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	writeImports(&b, rules, needUTF8, needRegexp)
	writePatternVars(&b, rules, needEmail)

	b.WriteString("// NewValidator returns the generated request validator. Assign it to\n")
	b.WriteString("// runtime.HTTPHandlerDependencies.Validator.\n")
	b.WriteString("func NewValidator() runtime.Validator { return generatedValidator{} }\n\n")
	b.WriteString("type generatedValidator struct{}\n\n")

	writeDispatch(&b, rules)
	for _, sr := range rules {
		writeStructFunc(&b, sr)
	}

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w\n%s", err, b.String())
	}
	return out, nil
}

// scanNeeds reports which optional imports the rules require.
func scanNeeds(rules []structRules) (utf8, regex, email bool) {
	for _, sr := range rules {
		for _, f := range sr.fields {
			if f.kind == kindString && (f.sizeMin != nil || f.sizeMax != nil) {
				utf8 = true
			}
			if f.pattern != "" {
				regex = true
			}
			if f.email {
				regex = true
				email = true
			}
		}
	}
	return
}

func writeImports(b *strings.Builder, rules []structRules, needUTF8, needRegexp bool) {
	paths := map[string]bool{"context": true, runtimeImport: true}
	if needUTF8 {
		paths["unicode/utf8"] = true
	}
	if needRegexp {
		paths["regexp"] = true
	}
	for _, sr := range rules {
		paths[sr.pkgPath] = true
	}
	var std, ext []string
	for p := range paths {
		if strings.Contains(p, ".") { // has a domain → third-party
			ext = append(ext, p)
		} else {
			std = append(std, p)
		}
	}
	sort.Strings(std)
	sort.Strings(ext)
	b.WriteString("import (\n")
	for _, p := range std {
		fmt.Fprintf(b, "\t%q\n", p)
	}
	if len(ext) > 0 {
		b.WriteString("\n")
		for _, p := range ext {
			fmt.Fprintf(b, "\t%q\n", p)
		}
	}
	b.WriteString(")\n\n")
}

// writePatternVars emits the package-level compiled regexes for @Pattern and,
// if used, the shared @Email pattern. All MustCompile calls are safe because
// Analyze rejects uncompilable patterns.
func writePatternVars(b *strings.Builder, rules []structRules, needEmail bool) {
	type pv struct{ name, raw string }
	var vars []pv
	if needEmail {
		vars = append(vars, pv{"validateEmailPattern", emailPattern})
	}
	for _, sr := range rules {
		for _, f := range sr.fields {
			if f.pattern != "" {
				vars = append(vars, pv{f.patternVar, f.pattern})
			}
		}
	}
	if len(vars) == 0 {
		return
	}
	sort.Slice(vars, func(i, j int) bool { return vars[i].name < vars[j].name })
	b.WriteString("var (\n")
	for _, v := range vars {
		fmt.Fprintf(b, "\t%s = regexp.MustCompile(%s)\n", v.name, goStringLit(v.raw))
	}
	b.WriteString(")\n\n")
}

func writeDispatch(b *strings.Builder, rules []structRules) {
	b.WriteString("// Validate dispatches on the bound request type (value or pointer). A type\n")
	b.WriteString("// without constraints passes, matching runtime.NoopValidator's contract.\n")
	b.WriteString("func (generatedValidator) Validate(_ context.Context, value any) error {\n")
	b.WriteString("\tswitch v := value.(type) {\n")
	for _, sr := range rules {
		qualified := sr.pkgName + "." + sr.name
		fn := structFuncName(sr)
		fmt.Fprintf(b, "\tcase %s:\n\t\treturn %s(v)\n", qualified, fn)
		fmt.Fprintf(b, "\tcase *%s:\n\t\treturn %s(*v)\n", qualified, fn)
	}
	b.WriteString("\t}\n\treturn nil\n}\n\n")
}

func writeStructFunc(b *strings.Builder, sr structRules) {
	fn := structFuncName(sr)
	fmt.Fprintf(b, "func %s(v %s.%s) error {\n", fn, sr.pkgName, sr.name)
	b.WriteString("\tvar errs []runtime.FieldError\n")
	for _, f := range sr.fields {
		writeFieldChecks(b, f)
	}
	b.WriteString("\tif len(errs) > 0 {\n\t\treturn runtime.NewValidationError(errs...)\n\t}\n\treturn nil\n}\n\n")
}

func writeFieldChecks(b *strings.Builder, f fieldRule) {
	expr := "v." + f.goName
	emit := func(cond, code, msg string) {
		fmt.Fprintf(b, "\tif %s {\n", cond)
		fmt.Fprintf(b, "\t\terrs = append(errs, runtime.FieldError{Field: %q, Code: %q, Message: %q})\n", f.wire, code, msg)
		b.WriteString("\t}\n")
	}
	if f.required {
		switch f.kind {
		case kindString:
			emit(expr+` == ""`, "required", f.wire+" is required")
		case kindLenable:
			emit("len("+expr+") == 0", "required", f.wire+" is required")
		}
	}
	if f.min != nil {
		emit(fmt.Sprintf("%s < %d", expr, *f.min), "min",
			fmt.Sprintf("%s must be at least %d", f.wire, *f.min))
	}
	if f.max != nil {
		emit(fmt.Sprintf("%s > %d", expr, *f.max), "max",
			fmt.Sprintf("%s must be at most %d", f.wire, *f.max))
	}
	if f.sizeMin != nil {
		emit(lenExpr(f, expr)+fmt.Sprintf(" < %d", *f.sizeMin), "size",
			fmt.Sprintf("%s must have at least %d %s", f.wire, *f.sizeMin, sizeUnit(f)))
	}
	if f.sizeMax != nil {
		emit(lenExpr(f, expr)+fmt.Sprintf(" > %d", *f.sizeMax), "size",
			fmt.Sprintf("%s must have at most %d %s", f.wire, *f.sizeMax, sizeUnit(f)))
	}
	if f.pattern != "" {
		emit(fmt.Sprintf("%s != \"\" && !%s.MatchString(%s)", expr, f.patternVar, expr),
			"pattern", f.wire+" has an invalid format")
	}
	if f.email {
		emit(fmt.Sprintf("%s != \"\" && !validateEmailPattern.MatchString(%s)", expr, expr),
			"email", f.wire+" must be a valid email address")
	}
}

// lenExpr renders the length expression for a size check: rune count for
// strings, len() for slices/maps/arrays.
func lenExpr(f fieldRule, expr string) string {
	if f.kind == kindString {
		return "utf8.RuneCountInString(" + expr + ")"
	}
	return "len(" + expr + ")"
}

func sizeUnit(f fieldRule) string {
	if f.kind == kindString {
		return "characters"
	}
	return "items"
}

func structFuncName(sr structRules) string {
	return "validate" + exported(sr.pkgName) + sr.name
}

// goStringLit renders a Go string literal, preferring a raw literal for regexes
// (which are full of backslashes) unless the value itself contains a backtick.
func goStringLit(s string) string {
	if !strings.Contains(s, "`") && !strings.Contains(s, "\n") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}
