// Code generated by goboot. DO NOT EDIT.

package nege2e

import (
	"github.com/zombocoder/goboot/compiler/testdata/negapp"
	"github.com/zombocoder/goboot/runtime"
	"net/http"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	DocController *negapp.DocController
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents() (*Components, error) {
	docController := negapp.NewDocController()

	return &Components{
		DocController: docController,
	}, nil
}

// makeDocControllerCreateHandler handles POST /docs.
func makeDocControllerCreateHandler(docController *negapp.DocController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		if err := runtime.NegotiateContent(r, []string{"application/json"}, []string{"application/json"}); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		var request negapp.Doc
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := docController.Create(ctx, request)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 201, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// makeDocControllerRenderHandler handles GET /docs/{id}.
func makeDocControllerRenderHandler(docController *negapp.DocController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		if err := runtime.NegotiateContent(r, []string{}, []string{"application/json"}); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		var request negapp.IDRequest
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := docController.Render(ctx, request)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 200, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// RegisterRoutes registers every generated handler on the mux.
func RegisterRoutes(mux *http.ServeMux, components *Components, deps runtime.HTTPHandlerDependencies) {
	mux.HandleFunc("POST /docs", makeDocControllerCreateHandler(components.DocController, deps))
	mux.HandleFunc("GET /docs/{id}", makeDocControllerRenderHandler(components.DocController, deps))
}

// NewApplication builds the components and assembles a runnable application.
func NewApplication(deps runtime.HTTPHandlerDependencies, addr string) (*runtime.Application, error) {
	components, err := buildComponents()
	if err != nil {
		return nil, err
	}
	var lc *runtime.Lifecycle
	mux := http.NewServeMux()
	RegisterRoutes(mux, components, deps)
	server := &http.Server{Addr: addr, Handler: mux}
	return &runtime.Application{Server: server, Lifecycle: lc, Scheduler: nil}, nil
}
