// Code generated by goboot. DO NOT EDIT.
// Request validator generated by the goboot validate plugin from
// @Required/@Min/@Max/@Size/@Pattern/@Email field annotations.

package generated

import (
	"context"
	"regexp"
	"unicode/utf8"

	"github.com/zombocoder/goboot/plugins/validate/testdata/api"
	"github.com/zombocoder/goboot/runtime"
)

var (
	validateEmailPattern                    = regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)
	validatePatternApiCreateUserRequestSlug = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)
)

// NewValidator returns the generated request validator. Assign it to
// runtime.HTTPHandlerDependencies.Validator.
func NewValidator() runtime.Validator { return generatedValidator{} }

type generatedValidator struct{}

// Validate dispatches on the bound request type (value or pointer). A type
// without constraints passes, matching runtime.NoopValidator's contract.
func (generatedValidator) Validate(_ context.Context, value any) error {
	switch v := value.(type) {
	case api.CreateUserRequest:
		return validateApiCreateUserRequest(v)
	case *api.CreateUserRequest:
		return validateApiCreateUserRequest(*v)
	case api.GetUserRequest:
		return validateApiGetUserRequest(v)
	case *api.GetUserRequest:
		return validateApiGetUserRequest(*v)
	}
	return nil
}

func validateApiCreateUserRequest(v api.CreateUserRequest) error {
	var errs []runtime.FieldError
	if v.Name == "" {
		errs = append(errs, runtime.FieldError{Field: "name", Code: "required", Message: "name is required"})
	}
	if utf8.RuneCountInString(v.Name) < 3 {
		errs = append(errs, runtime.FieldError{Field: "name", Code: "size", Message: "name must have at least 3 characters"})
	}
	if utf8.RuneCountInString(v.Name) > 40 {
		errs = append(errs, runtime.FieldError{Field: "name", Code: "size", Message: "name must have at most 40 characters"})
	}
	if v.Email == "" {
		errs = append(errs, runtime.FieldError{Field: "email", Code: "required", Message: "email is required"})
	}
	if v.Email != "" && !validateEmailPattern.MatchString(v.Email) {
		errs = append(errs, runtime.FieldError{Field: "email", Code: "email", Message: "email must be a valid email address"})
	}
	if v.Age < 0 {
		errs = append(errs, runtime.FieldError{Field: "age", Code: "min", Message: "age must be at least 0"})
	}
	if v.Age > 150 {
		errs = append(errs, runtime.FieldError{Field: "age", Code: "max", Message: "age must be at most 150"})
	}
	if v.Slug != "" && !validatePatternApiCreateUserRequestSlug.MatchString(v.Slug) {
		errs = append(errs, runtime.FieldError{Field: "slug", Code: "pattern", Message: "slug has an invalid format"})
	}
	if len(v.Tags) > 5 {
		errs = append(errs, runtime.FieldError{Field: "tags", Code: "size", Message: "tags must have at most 5 items"})
	}
	if len(errs) > 0 {
		return runtime.NewValidationError(errs...)
	}
	return nil
}

func validateApiGetUserRequest(v api.GetUserRequest) error {
	var errs []runtime.FieldError
	if v.ID == "" {
		errs = append(errs, runtime.FieldError{Field: "id", Code: "required", Message: "id is required"})
	}
	if len(errs) > 0 {
		return runtime.NewValidationError(errs...)
	}
	return nil
}
