// Code generated by goboot. DO NOT EDIT.

package cachee2e

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/zombocoder/goboot/compiler/testdata/cacheapp"
	"github.com/zombocoder/goboot/runtime"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Store             *cacheapp.StoreService
	StoreServiceProxy cacheapp.Store
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents(proxyDeps runtime.ProxyDependencies) (*Components, error) {
	store := cacheapp.NewStoreService()
	storeServiceProxy := NewStoreServiceProxy(store, proxyDeps)

	return &Components{
		Store:             store,
		StoreServiceProxy: storeServiceProxy,
	}, nil
}

// StoreServiceProxy is the generated interception proxy for StoreService.
type StoreServiceProxy struct {
	target       *cacheapp.StoreService
	transaction  runtime.TransactionManager
	tracer       runtime.Tracer
	metrics      runtime.MethodMetrics
	authorizer   runtime.Authorizer
	logger       runtime.MethodLogger
	audit        runtime.AuditSink
	breakers     runtime.CircuitBreakerProvider
	rateLimiters runtime.RateLimiterProvider
	bulkheads    runtime.BulkheadProvider
	cache        runtime.Cache
}

// NewStoreServiceProxy builds the StoreServiceProxy.
func NewStoreServiceProxy(target *cacheapp.StoreService, deps runtime.ProxyDependencies) *StoreServiceProxy {
	return &StoreServiceProxy{target: target, transaction: deps.Transactions, tracer: deps.Tracer, metrics: deps.Metrics, authorizer: deps.Authorizer, logger: deps.Logger, audit: deps.Audit, breakers: deps.Breakers, rateLimiters: deps.RateLimiters, bulkheads: deps.Bulkheads, cache: deps.Cache}
}

func (p *StoreServiceProxy) Get(a0 context.Context, a1 string) (r0 string, err error) {
	cacheKey := "store:" + fmt.Sprint(a1)
	if data, ok, _ := p.cache.Get(a0, cacheKey); ok {
		if json.Unmarshal(data, &r0) == nil {
			return
		}
	}
	r0, err = p.target.Get(a0, a1)
	if err == nil {
		if data, mErr := json.Marshal(r0); mErr == nil {
			_ = p.cache.Set(a0, cacheKey, data, 60000000000)
		}
	}
	return
}

func (p *StoreServiceProxy) Put(a0 context.Context, a1 string, a2 string) (err error) {
	cacheEvictKey := "store:" + fmt.Sprint(a1)
	err = p.target.Put(a0, a1, a2)
	if err == nil {
		_ = p.cache.Delete(a0, cacheEvictKey)
	}
	return
}
