// Code generated by goboot. DO NOT EDIT.

package wiring

import (
	"github.com/zombocoder/goboot/compiler/testdata/diapp/config"
	"github.com/zombocoder/goboot/compiler/testdata/diapp/controller"
	"github.com/zombocoder/goboot/compiler/testdata/diapp/domain"
	"github.com/zombocoder/goboot/compiler/testdata/diapp/repo"
	"github.com/zombocoder/goboot/compiler/testdata/diapp/service"
	"github.com/zombocoder/goboot/runtime"
	"net/http"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Config         *config.Config
	IdGenerator    domain.IDGenerator
	UserController *controller.UserController
	UserRepository *repo.PostgresUserRepository
	UserService    *service.UserService
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents() (*Components, error) {
	config2 := &config.Config{}
	idGenerator := config.ProvideIDGenerator()
	userRepository := repo.NewPostgresUserRepository()
	userService := service.NewUserService(userRepository, idGenerator)
	userController := controller.NewUserController(userService)

	return &Components{
		Config:         config2,
		IdGenerator:    idGenerator,
		UserController: userController,
		UserRepository: userRepository,
		UserService:    userService,
	}, nil
}

// makeUserControllerCreateUserHandler handles POST /api/v1/users.
func makeUserControllerCreateUserHandler(userController *controller.UserController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		var request controller.CreateUserRequest
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := userController.CreateUser(ctx, request)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 201, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// makeUserControllerGetUserHandler handles GET /api/v1/users/{id}.
func makeUserControllerGetUserHandler(userController *controller.UserController, deps runtime.HTTPHandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		defer runtime.Recover(ctx, w, r, deps.ErrorHandler)

		var request controller.GetUserRequest
		if err := deps.Binder.Bind(ctx, r, &request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.Validator.Validate(ctx, request); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		response, err := userController.GetUser(ctx, request)
		if err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
		if err := deps.ResponseWriter.Write(ctx, w, 200, response); err != nil {
			deps.ErrorHandler.Handle(ctx, w, r, err)
			return
		}
	}
}

// RegisterRoutes registers every generated handler on the mux.
func RegisterRoutes(mux *http.ServeMux, components *Components, deps runtime.HTTPHandlerDependencies) {
	mux.HandleFunc("POST /api/v1/users", makeUserControllerCreateUserHandler(components.UserController, deps))
	mux.HandleFunc("GET /api/v1/users/{id}", makeUserControllerGetUserHandler(components.UserController, deps))
}

// NewApplication builds the components and assembles a runnable application.
func NewApplication(deps runtime.HTTPHandlerDependencies, addr string) (*runtime.Application, error) {
	components, err := buildComponents()
	if err != nil {
		return nil, err
	}
	var lc *runtime.Lifecycle
	mux := http.NewServeMux()
	RegisterRoutes(mux, components, deps)
	server := &http.Server{Addr: addr, Handler: mux}
	return &runtime.Application{Server: server, Lifecycle: lc}, nil
}
