// Code generated by goboot. DO NOT EDIT.

package wiring

import (
	"github.com/zombocoder/goboot/compiler/testdata/diapp/config"
	"github.com/zombocoder/goboot/compiler/testdata/diapp/controller"
	"github.com/zombocoder/goboot/compiler/testdata/diapp/domain"
	"github.com/zombocoder/goboot/compiler/testdata/diapp/repo"
	"github.com/zombocoder/goboot/compiler/testdata/diapp/service"
)

// Components holds the constructed singleton components of the application.
type Components struct {
	Config         *config.Config
	IdGenerator    domain.IDGenerator
	UserController *controller.UserController
	UserRepository *repo.PostgresUserRepository
	UserService    *service.UserService
}

// buildComponents constructs every singleton component in dependency order.
func buildComponents() (*Components, error) {
	config2 := &config.Config{}
	idGenerator := config.ProvideIDGenerator()
	userRepository := repo.NewPostgresUserRepository()
	userService := service.NewUserService(userRepository, idGenerator)
	userController := controller.NewUserController(userService)

	return &Components{
		Config:         config2,
		IdGenerator:    idGenerator,
		UserController: userController,
		UserRepository: userRepository,
		UserService:    userService,
	}, nil
}
